language: c
sudo: required
services:
  - docker
script:
    bash -ex .travis-ci.sh
dist:
  - bionic
arch:
  - amd64
  - arm64
  - ppc64le
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.1
  - OCAML_VERSION=4.08.1
  - OCAML_VERSION=4.09.1
  - OCAML_VERSION=4.10.0
