name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.10.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pandoc
        run: brew install pandoc

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}

      - name: Install dune
        if: ${{ matrix.os == 'macos-latest' }}
        run: opam install dune>=2.9.0

      - name: Build HTML book
        if: runner.os == 'Linux'
        run: opam exec -- dune build @site

      - name: Run promotion tests
        run: opam exec -- dune runtest

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' && runner.os == 'Linux'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/static
